### ISSUE TITLE
Fixed CSS for the download buttons

### ISSUE THREAD

**Issue by gzubka** [MiniDude22/Pandora-Downloader#10]
.pd-download-single {
    color: #224099;
    font-size: 0.9em;
    position: absolute;
    left: 200px;
    top: -24px;
    z-index: 20000;
}

.pd-download-continuous {
    position: absolute;
    z-index: 20000;
    left: 0px;
    top: -24px;
    font-size: 0.9em;
    color: #224099;
}

.pd-download-continuous[disabled], .pd-download-single[disabled] {
    color: rgba(34, 64, 153, 0.55);
}

.pd-infobox {
    display: none;
    color: black;
    position: fixed;
    bottom: 0px;
    right: 0px;
    background-color: white;
    border-left: 2px black solid;
    border-top: 2px black solid;
    padding: 10px;
    z-index: 20000;
}

**Comment by x106x** [comment]
Thanks, very helpful.

**Comment by MiniDude22** [comment]
Fixed in 62654dd
