### ISSUE TITLE
Combined fixes into one archive

### ISSUE THREAD

**Issue by x106x** [MiniDude22/Pandora-Downloader#13]
https://www.dropbox.com/s/1a3816s57sh0rki/PandoraDownloader.7z?dl=0

There are still issues that need fixed because it's original code.  This is just the CSS and unicode text issue fixes combined since the original branch seems dead.

**Comment by MiniDude22** [comment]
Hi, please let me know the other issues that needed fixed. I think i got most of them in 62654dd

**Comment by x106x** [comment]
The other issues involve the previous song being downloaded and named as the current song.  If you switch between continuous and manual and click download, that's what happens a lot of the time.  I've only done this because continuous doesn't always trigger a download.

**Comment by x106x** [comment]
Testing the new commit now and so far it actually acts different than the last commit.  It's immediately responsive to the skip button so you may have resolved the only issues I've had.
