### ISSUE TITLE
Downloading the song can only pull the currently playing song

### ISSUE THREAD

**Issue by brianlilly** [MiniDude22/Pandora-Downloader#2]
When scanning back in tracks, it still only downloads the currently playing song, not the one highlighted, despite messages to the contrary.

**Comment by MiniDude22** [comment]
With version 2.0 the messages should be fixed to let you know it can only download the currently playing song right now. Backtracking would be an interesting feature, but the links for the songs expire after a certain amount of time so adding that functionality would be tricky.
