### ISSUE TITLE
Not an MP4 file when using premium service

### ISSUE THREAD

**Issue by dash74** [MiniDude22/Pandora-Downloader#9]
This is working when selecting the lower bit rate, but when selecting use higher quality audio within Pandora's settings. It is throwing an error.

**Comment by gzubka** [comment]
I am having the same issue.

**Comment by MiniDude22** [comment]
I do not have a premium account with with to test and solve this. Sorry.

**Comment by joshricker** [comment]
I would like to add that this is the error i am getting, but it is saving them just fine. Is there anyway to make the auto download work and just ignore this error? Other wise i have to click download on every song. Or even a donation link to get you a premium account, as i would happily get you a few months for your time.

**Comment by joshricker** [comment]
Well i decided to take a go at it myself and got it mostly working, it seems the premium option gives you mp3 files so I used mutagens easy id3 and it seems to have worked. If anyone else is wanting to try it replace your flask_server with the following [this](https://pastebin.com/PjsGNDqL).
